export const OpreatorData = [
  {
    id: 0,
    icontype: 'FontAwesome5',
    iconName: 'coins',
    title: 'Send Money',
    route: '',
  },
  {
    id: 1,
    icontype: 'Entypo',
    iconName: 'stopwatch',
    title: 'Scheduled Payments',
    route: '',
  },
  {
    id: 2,
    icontype: 'FontAwesome',
    iconName: 'calendar-check-o',
    title: 'Direct Debits',
    route: '',
  },
  {
    id: 3,
    icontype: 'AntDesign',
    iconName: 'switcher',
    title: 'Payment of Bills',
    route: '',
  },
  {
    id: 4,
    icontype: 'AntDesign',
    iconName: 'wallet',
    title: 'Wallet Cards',
    route: '',
  },
  {
    id: 5,
    icontype: 'MaterialCommunityIcons',
    iconName: 'cellphone',
    title: 'Rechare a cellphone',
    route: '',
  },
];

export const AccountHistoryData = [
  {
    id: 1,
    ammount: '21850',
    date: '04 aug 2023',
    type: 'received',
    from: 'Received 21850 € from el corte',
    icontype: 'FontAwesome',
    iconName: 'money',
    iconColor: 'green',
  },
  {
    id: 1,
    ammount: '1500',
    date: '12 july 2023',
    type: 'withdrawal',
    from: 'Transfer to Honest food court via Debit Card',
    icontype: 'Ionicons',
    iconName: 'fast-food',
    iconColor: 'orange',
  },
  {
    id: 2,
    ammount: '500',
    date: '10 july 2023',
    type: 'received',
    from: 'Received 500 € from axis bank ACC.',
    icontype: 'FontAwesome',
    iconName: 'money',
    iconColor: 'green',
  },
  {
    id: 3,
    ammount: '500',
    date: '9 july 2023',
    type: 'received',
    from: 'Received 500 € from axis bank ACC.',
    icontype: 'FontAwesome',
    iconName: 'money',
    iconColor: 'green',
  },
  {
    id: 4,
    ammount: '553',
    date: '8 july 2023',
    type: 'received',
    from: 'Received 553 € from hdfc bank ACC.',
    icontype: 'FontAwesome',
    iconName: 'money',
    iconColor: 'green',
  },
  {
    id: 5,
    ammount: '500',
    date: '7 july 2023',
    type: 'withdrawal',
    from: 'Transfer to hdfc pvt ltd.',
    icontype: 'MaterialIcons',
    iconName: 'monetization-on',
  },
  {
    id: 6,
    ammount: '1638,62',
    date: '6 july 2023',
    type: 'withdrawal',
    from: 'Transfer 1638,62 € through Paypal/Bank Transfer',
    icontype: 'Entypo',
    iconName: 'paypal',
    iconColor: 'blue',
  },
  {
    id: 7,
    ammount: '23800',
    date: '3 july 2023',
    type: 'received',
    from: 'Received 23800 euro from axis bank ACC.',
    icontype: 'FontAwesome',
    iconName: 'money',
    iconColor: 'green',
  },
];
